name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.iso.commit.svg
          token: ${{ secrets.TOKEN }}
          committer_token: ${{ secrets.TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.used.svg
          token: ${{ secrets.TOKEN }}
          committer_token: ${{ secrets.TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 20
